name: Continuous integration Windows

on: [pull_request, push]

jobs:
    build_and_test:
      name: Rust project
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
          with:
            toolchain: stable
        - run: cargo build --release --all-features
        - run: cargo test --all-features