name: Continuous integration

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    release-binary:
      name: Compile and upload
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
          with:
            toolchain: stable
        - run: cargo build --release --all-features
        - run: >-
          gh release create ${{ github.ref_name }}
          "./target/release/temp-conv"
          --generate-notes
          --title "Version ${{ github.ref_name }}"
