name: Continuous integration

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    release-binary:
      name: Compile and upload
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
          with:
            toolchain: stable
        - run: cargo build --release --all-features
        - uses: softprops/action-gh-release@v2
          with:
            files: ./target/release/temp-conv
        
                  